name: 🚀 Release
on:
  push:
    tags: ["*"]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:
    name: 🛠️ Build JS Artifact and Changelog
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🥟 Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install Dependencies
        run: bun install

      - name: 🔨 Build seda-cosmos-accelerator
        run: |
          bun run build

      - name: 📝 Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: false
          skip-commit: true
          skip-tag: true
          skip-git-pull: true
          git-push: false

      - name: ⬆️ Upload JS artifact and checksum for release
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            dist/seda-cosmos-accelerator-linux-arm64
            dist/seda-cosmos-accelerator-linux-x64

  create_release:
    name: 🎉 Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: 📥 Download all release assets
        uses: actions/download-artifact@v4
        with:
          name: release-assets
          path: ./release-assets

      - name: 🎉 Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          body: ${{ needs.build.outputs.changelog }}
          artifacts: ./release-assets/**/*
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          tag: ${{ github.ref_name }} 
